shell = "zsh"

[plugins]
[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[plugins.powerlevel10k]
github = 'romkatv/powerlevel10k'
apply = ['source']

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['defer']

[plugins.enhancd]
github = 'b4b4r07/enhancd'
apply = ['defer']

[plugins.fzf]
github = 'junegunn/fzf'
apply = ['fzf-install', 'fzf-source']

# [plugins.zsh-autocomplete]
# github = 'marlonrichert/zsh-autocomplete'
# apply = ['defer']

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
fzf-install = "{{ dir }}/install --bin > /dev/null \n path=($path {{ dir }}/bin(N-/))\n"
fzf-source = "source <(fzf --zsh)"

