shell = "zsh"

[plugins]
[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['defer']

[plugins.enhancd]
github = 'b4b4r07/enhancd'
apply = ['defer']

[plugins.fzf]
github = 'junegunn/fzf'
apply = ['fzf-install', 'fzf-source']

[templates]
PATH = 'export PATH="$PATH:{{ dir }}"'
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
fzf-install = "{{ dir }}/install --bin > /dev/null \n[[ ! $PATH == *{{ dir }}* ]] && export PATH=\"$PATH:{{ dir }}/bin\"\n"
fzf-source = "{% for file in files %}source \"{{ file }}\"\n{% endfor %}"

